name: Validate Headers

on:
  pull_request:
    branches: 
      - 'brizo-master'

jobs:
   verify-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CAN Repo
        uses: actions/checkout@v2
      - name: Cache Arm C++ Compiler
        id: cache-compiler
        uses: actions/cache@v2
        with:
          path: gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          key: ${{ runner.os }}-arm-none-eabi-2019-q4-x86  ## Update this key if/when the version changes
      - name: Download Arm C++ Compiler
        if: steps.cache-compiler.outputs.cache-hit != 'true'
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
      - name: Install Arm C++ Compiler
        run: |
          mkdir -p $GITHUB_WORKSPACE/install/
          tar xvf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 -C $GITHUB_WORKSPACE/install/ >/dev/null
          echo "$GITHUB_WORKSPACE/install/gcc-arm-none-eabi-9-2019-q4-major/bin" >> $GITHUB_PATH
          chmod +x $GITHUB_WORKSPACE/install/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-c++
      - name: Validate CAN ID Header
        if: always()
        run: |
          arm-none-eabi-c++ -std=c++11 -fsyntax-only -Wall -Wextra -Wno-deprecated $GITHUB_WORKSPACE/can_id.h
      - name: Validate CAN DATA Header
        if: always()
        run: |
          arm-none-eabi-c++ -std=c++11 -fsyntax-only -Wall -Wextra -Wno-deprecated $GITHUB_WORKSPACE/can_data.h   


