name: Validate JSONs

on:
  push:
    paths: 
      - "canDef.json"
      - "schema.json"
    branches:
      - '**'
      - '!brizo-master' #All branches except brizo master, which validates in the utilization workflow

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate CAN Def
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /canDef.json
      - name: Verify No Duplicates
        run: |
          python .github/scripts/check_duplicates.py

