version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the actions directories
    directory: ".github/actions/*/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
