# See: https://en.wikipedia.org/wiki/CAN_bus#Frames
overhead-bits:
  start: 1
  id: 11
  ide: 1
  reserved0: 1
  crc: 15
  crcDelim: 1
  ack: 1
  ackDelim: 1
  EOF: 7
data-type-bits:
  FloatLE: 32
  Uint64LE: 64
  Int64LE: 64
  Uint32LE: 32
  Int32LE: 32
  Uint16LE: 16
  Int16LE: 16
  Uint8LE: 8
  Int8LE: 8
  BitMap8LE: 8
  BitMap16LE: 16
  BitMap32LE: 32
bus_speed: 500
debug_messages:
  min: 0x400
  max: 0x4FF
colors:
  critical: 50 
  warn: 30



